config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "tops#index"
  get "post_mathos" => "tops#post_mathos"
  get "about" => "tops#about"
  get "news" => "tops#news"
end

app/models/mathos.rb
class Mathos
  include Redis::Objects
  counter :total_mathos

  def id
    1
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  before_action :set_mathos
  def index
  end

  def about
  end

  def news
  end

  def post_mathos
    @mathos.total_mathos.increment
  end

  private

  def set_mathos
    @mathos = Mathos.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HI, HOW ARE YOU</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tops/_footer.html.slim
.container.fixed-bottom
  = render partial: "since_site_established"
  = render partial: "mathos_meter"

app/views/tops/_mathos_meter.html.slim
footer.container.pt-3
  .row.align-items-center
    .col-3
    .col-6.d-grid.gap-2
      = link_to "MATHOS!!", post_mathos_path, remote: true, class: "btn btn-outline-danger btn-lg"
    .col-3
  .row.pt-3
    h1.text-center Super Mathos Meter Online
  .row.pt-3
    h1.text-center
      .total_mathos
        = "#{@mathos.total_mathos.value} Mathos"

app/views/tops/_since_site_established.html.slim
.container.bg-worning.pt-2.pb-3
  h2.text-center#item
  h2.text-center since site established

app/views/tops/about.html.slim
.all-container
  header.container.pt-2.pb-3
    .row
      .col-6.text-center.d-grid.gap-2
        button.btn.btn-block.btn-lg style="transform: rotate(0);"
          = link_to "TOP", root_path, class: "text-decoration-none text-secondary stretched-link"
      .col-6.text-center.d-grid.gap-2.header-btn-size
        button.btn.btn-block.btn-lg style="transform: rotate(0);"
          = link_to "NEWS", news_path, class: "text-decoration-none text-secondary stretched-link"
  .container.pt-5.pb-3
    article.fs-3.text-center
      p This is a site that has no particular meaning.
      p The top image is Daniel Johnston's CD jacket.
      p If you like it, please buy it.
      p The mathos meter is a pakuri of the Omokoro.
      p Omokoro is an interesting site, so please go if you like.
  = render partial: "footer"

app/views/tops/index.html.slim
.all-container
  header.container.pt-2.pb-3
    .row
      .col-6.text-center.d-grid.gap-2
        button.btn.btn-block.btn-lg style="transform: rotate(0);"
          = link_to "ABOUT", about_path, class: "text-decoration-none text-secondary stretched-link"
      .col-6.text-center.d-grid.gap-2.header-btn-size
        button.btn.btn-block.btn-lg style="transform: rotate(0);"
          = link_to "NEWS", news_path, class: "text-decoration-none text-secondary stretched-link"
  .container.pt-5.pb-3
    img-area
      article#index.container.next-open
        section#mv
          h1 HI HOW ARE YOU
  = render partial: "footer"

app/views/tops/news.html.slim
.all-container
  header.container.pt-2.pb-3
    .row
      .col-6.text-center.d-grid.gap-2
        button.btn.btn-block.btn-lg style="transform: rotate(0);"
          = link_to "TOP", root_path, class: "text-decoration-none text-secondary stretched-link"
      .col-6.text-center.d-grid.gap-2.header-btn-size
        button.btn.btn-block.btn-lg style="transform: rotate(0);"
          = link_to "ABOUT", about_path, class: "text-decoration-none text-secondary stretched-link"
  .container.pt-5.pb-3
    article.fs-3.text-center
      p Comming soon ?
  = render partial: "footer"

app/views/tops/post_mathos.js.erb
$(".total_mathos").html('<%="#{@mathos.total_mathos.value} Mathos" %>')